### ISSUE TITLE
Missing Mdl_users.php dan stuck "starting application"?

### ISSUE THREAD

**Issue by bektigalan** [copolatoz/WePOS-Free#1]
[https://github.com/copolatoz/WePOS-Free/blame/master/application/modules/auth/controllers/Users.php](url)
`function __construct()
	{
		parent::__construct();
		$this->load->model('mdl_users', 'm');	
	}`
fungsi construct memanggil model mdl_users namun di folder auth tidak terdapat nama model tersebut, mau fungsi di model manapun, mungkin missing?
![ss1](https://user-images.githubusercontent.com/7407859/37500257-0f8f6ef8-28fb-11e8-8f77-ec9b32d05b37.png)
setelah login wepos stuck disini min

**Comment by copolatoz** [comment]
sebelumnya sdh diupdate akhir tahun lalu, ternyata file di github tidak update..
tp sudah di push ulang, coba di pull lagi.. tengkyu..

**Comment by bektigalan** [comment]
okay, thanks min

**Comment by copolatoz** [comment]
pastikan sudah di close / logout.. clear cache dulu
